### ISSUE TITLE
Running on Windows, whisper.cpp silently errors

### ISSUE THREAD

**Issue by JIBSIL** [ggerganov/whisper.cpp#722] opened 2023-04-05 19:10 UTC
I downloaded the most recent build from Github Releases, extracted it and ran this command:

`main -m ggml-model-whisper-medium.en-q4_0.bin -f jfk.wav`

with an output of 

```
whisper_init_from_file: loading model from 'ggml-model-whisper-medium.en-q4_0.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51864
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 1024
whisper_model_load: n_audio_head  = 16
whisper_model_load: n_audio_layer = 24
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 1024
whisper_model_load: n_text_head   = 16
whisper_model_load: n_text_layer  = 24
whisper_model_load: n_mels        = 80
whisper_model_load: f16           = 2
whisper_model_load: type          = 4
whisper_model_load: mem required  = 1720.00 MB (+   43.00 MB per decoder)
whisper_model_load: kv self size  =   42.00 MB
whisper_model_load: kv cross size =  140.62 MB
whisper_model_load: adding 1607 extra tokens
whisper_model_load: model ctx     = 1462.35 MB
```

No other output was provided and the process died.

Any tips?

**Comment by misutoneko** [comment] 2023-04-05 22:58
Duplicate of #655. I don't think 4-bit is supported in master yet.
Btw the version in the 4-bit branch shows ftype as "q4_0", so that's one way to tell if you have the right version.

**Comment by Ewgenii** [comment] 2023-04-09 13:22
Hi! I used the version [v1.2.1](https://github.com/ggerganov/whisper.cpp/releases/tag/v1.2.1) ([whisper-bin-x64.zip](https://github.com/ggerganov/whisper.cpp/releases/download/v1.2.1/whisper-bin-x64.zip) to be exact). I have a 64-bit operating system with 32 gigabytes of RAM. On Windows it is exactly the same problem.

**Comment by misutoneko** [comment] 2023-04-09 21:29
So the solution is the same, don't try to use 4-bit models with the released binaries.
Check your model files. If there's q4_0 or q4_1 in the file name, those won't work and you need to download the correct ones.

The crash is unfortunate, I suppose there will eventually be checks in place to prevent that.
There's no ETA for merging 4-bit stuff (that I know of) though, so in the meanwhile you just need to pay attention to use the correct model files.

One more thing, I assume these q4 stamped files were *manually* downloaded and not with the models/download-ggml-model* scripts, right? The scripts *should* give you the correct files (if they don't, that's a bug).

**Comment by Ewgenii** [comment] 2023-04-09 21:51
I just downloaded the models from a link like https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-%model%.bin. I tried "large" and "medium".

Which model do you recommend?

**Comment by misutoneko** [comment] 2023-04-09 23:30
Actually, those are the original ggml models and they should work OK. So your segfault is caused by something else.

As for which model to use, I recommend medium.en as it usually does the job. But the selection of model depends on many factors, even small.en is already pretty good. I usually don't use the large models much because of my hw restrictions, but in some cases they're the only ones that get things right, especially when it comes to timestamps.
The multilingual ones can sometimes give you better results than the .en ones, even with english source material.

**Comment by Ewgenii** [comment] 2023-04-10 07:16
Immediately after downloading and checked the SHA of each model, the values were the same as specified in [readme](https://github.com/ggerganov/whisper.cpp#readme). Anyway, on Windows64 the standard models do not work with the 1.2.1 release version (also with 1.2.0). Why exactly is unclear, because there is no error text. I would think that the problem is in the WAV file, but I convert it standard via ffmpeg (`ffmpeg.exe -y -i in.ogg -ar 16000 -ac 1 -c:a pcm_s16le out.wav`). The problem still persists.

**Comment by misutoneko** [comment] 2023-04-10 17:27
The prebuilt binaries seem to require AVX2. You didn't mention your CPU so maybe that's the problem?
I get "illegal instruction" on Linux (Wine) but idk how it behaves on real Windows.

**Comment by Ewgenii** [comment] 2023-04-10 17:33
Yes, you are right, I forgot to mention. My processor is an Intel Xeon E5 2650 v2. 

The text that the program outputs before it terminates:

`system_info: n_threads = 12 / 16 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 0 | NEON = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 0 | VSX = 0 |`

**Comment by ggerganov** [comment] 2023-04-14 17:10
4-bit support is coming soon.
Closing for now since at the moment it is not supported on `master`

**Closed by ggerganov** 2023-04-14 17:10 UTC
