### ISSUE TITLE
[FR] Upload CoreML models so that installing Xcode becomes unnecessary

### ISSUE THREAD

**Issue by NightMachinery** [ggerganov/whisper.cpp#830] opened 2023-04-28 21:15 UTC
Xcode is huge, and downloading it from Apple's crappy app store is extremely difficult in countries with bad internet connections like Iran. (This is not so much a problem of speed; the connection is unstable and Apple's downloaders are not at all resilient to network instability.)

Related:
- https://github.com/ggerganov/whisper.cpp/issues/770

**Comment by dugubuyan** [comment] 2023-05-11 08:51
where can i get the CoreML models?

**Comment by timmermansjoy** [comment] 2023-05-12 12:18
@dugubuyan read the readme

**Comment by bmurray** [comment] 2023-06-15 20:56
I second this. Not because XCode, but because I kinda hate dealing with Python, and I can't expect customers to download and process the models. Currently it just downloads the standard, slower models. I'm not sure about the logistics of putting the models on Huggingface.

**Comment by bmurray** [comment] 2023-06-16 00:24
I've opened a PR on huggingface with the zipped versions. I can write some shell scripts to pull those, and update the docs. 

https://huggingface.co/ggerganov/whisper.cpp/discussions/4/files

**Comment by ggerganov** [comment] 2023-06-25 11:05
@bmurray Thanks for this - the zipped versions are now merged on HF

**Closed by ggerganov** 2023-06-25 11:05 UTC

**Comment by NightMachinery** [comment] 2024-07-02 21:10
@ggerganov Can you add the CoreML versions of the distilled models, too?

- https://huggingface.co/distil-whisper/distil-large-v3/tree/main

**Comment by NightMachinery** [comment] 2024-07-03 00:14
To use the uploaded CoreML models, do we need to also download the original versions? The example in the readme implies so:
```
$ ./main -m models/ggml-base.en.bin -f samples/jfk.wav

...

whisper_init_state: loading Core ML model from 'models/ggml-base.en-encoder.mlmodelc'
whisper_init_state: first run on a device may take a while ...
whisper_init_state: Core ML model loaded

system_info: n_threads = 4 / 10 | AVX = 0 | AVX2 = 0 | AVX512 = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | VSX = 0 | COREML = 1 |

...
```

**Comment by kabyanil** [comment] 2024-12-01 17:17
> To use the uploaded CoreML models, do we need to also download the original versions? 

I can confirm that is correct. However, when I run inference on the provided sample audio, I receive all the logs except only the transcription output. Here is my entire output -

```
➜  whisper.cpp ./main -m ./models/ggml-small.bin -f ./samples/jfk.wav -l en
whisper_init_from_file_with_params_no_state: loading model from './models/ggml-small.bin'
whisper_init_with_params_no_state: use gpu    = 1
whisper_init_with_params_no_state: flash attn = 0
whisper_init_with_params_no_state: gpu_device = 0
whisper_init_with_params_no_state: dtw        = 0
whisper_init_with_params_no_state: devices    = 3
whisper_init_with_params_no_state: backends   = 3
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 768
whisper_model_load: n_audio_head  = 12
whisper_model_load: n_audio_layer = 12
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 768
whisper_model_load: n_text_head   = 12
whisper_model_load: n_text_layer  = 12
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 1
whisper_model_load: qntvr         = 0
whisper_model_load: type          = 3 (small)
whisper_model_load: adding 1608 extra tokens
whisper_model_load: n_langs       = 99
whisper_default_buffer_type: using device Metal (Intel(R) Iris(TM) Graphics 6100)
whisper_model_load:    Metal total size =   487.01 MB
whisper_model_load: model size    =  487.01 MB
whisper_backend_init_gpu: using Metal backend
ggml_metal_init: allocating
ggml_metal_init: found device: Intel(R) Iris(TM) Graphics 6100
ggml_metal_init: picking default device: Intel(R) Iris(TM) Graphics 6100
ggml_metal_init: using embedded metal library
ggml_metal_init: GPU name:   Intel(R) Iris(TM) Graphics 6100
ggml_metal_init: GPU family: MTLGPUFamilyCommon2 (3002)
ggml_metal_init: simdgroup reduction   = false
ggml_metal_init: simdgroup matrix mul. = false
ggml_metal_init: has bfloat            = false
ggml_metal_init: use bfloat            = false
ggml_metal_init: hasUnifiedMemory      = true
ggml_metal_init: recommendedMaxWorkingSetSize  =  1610.61 MB
ggml_metal_init: skipping kernel_soft_max_f16                      (not supported)
ggml_metal_init: skipping kernel_soft_max_f16_4                    (not supported)
ggml_metal_init: skipping kernel_soft_max_f32                      (not supported)
ggml_metal_init: skipping kernel_soft_max_f32_4                    (not supported)
ggml_metal_init: skipping kernel_get_rows_bf16                     (not supported)
ggml_metal_init: skipping kernel_rms_norm                          (not supported)
ggml_metal_init: skipping kernel_group_norm                        (not supported)
ggml_metal_init: skipping kernel_mul_mv_f32_f32                    (not supported)
ggml_metal_init: skipping kernel_mul_mv_bf16_f32                   (not supported)
ggml_metal_init: skipping kernel_mul_mv_bf16_f32_1row              (not supported)
ggml_metal_init: skipping kernel_mul_mv_bf16_f32_l4                (not supported)
ggml_metal_init: skipping kernel_mul_mv_bf16_bf16                  (not supported)
ggml_metal_init: skipping kernel_mul_mv_f16_f32                    (not supported)
ggml_metal_init: skipping kernel_mul_mv_f16_f32_1row               (not supported)
ggml_metal_init: skipping kernel_mul_mv_f16_f32_l4                 (not supported)
ggml_metal_init: skipping kernel_mul_mv_f16_f16                    (not supported)
ggml_metal_init: skipping kernel_mul_mv_q4_0_f32                   (not supported)
ggml_metal_init: skipping kernel_mul_mv_q4_1_f32                   (not supported)
ggml_metal_init: skipping kernel_mul_mv_q5_0_f32                   (not supported)
ggml_metal_init: skipping kernel_mul_mv_q5_1_f32                   (not supported)
ggml_metal_init: skipping kernel_mul_mv_q8_0_f32                   (not supported)
ggml_metal_init: skipping kernel_mul_mv_q2_K_f32                   (not supported)
ggml_metal_init: skipping kernel_mul_mv_q3_K_f32                   (not supported)
ggml_metal_init: skipping kernel_mul_mv_q4_K_f32                   (not supported)
ggml_metal_init: skipping kernel_mul_mv_q5_K_f32                   (not supported)
ggml_metal_init: skipping kernel_mul_mv_q6_K_f32                   (not supported)
ggml_metal_init: skipping kernel_mul_mv_iq2_xxs_f32                (not supported)
ggml_metal_init: skipping kernel_mul_mv_iq2_xs_f32                 (not supported)
ggml_metal_init: skipping kernel_mul_mv_iq3_xxs_f32                (not supported)
ggml_metal_init: skipping kernel_mul_mv_iq3_s_f32                  (not supported)
ggml_metal_init: skipping kernel_mul_mv_iq2_s_f32                  (not supported)
ggml_metal_init: skipping kernel_mul_mv_iq1_s_f32                  (not supported)
ggml_metal_init: skipping kernel_mul_mv_iq1_m_f32                  (not supported)
ggml_metal_init: skipping kernel_mul_mv_iq4_nl_f32                 (not supported)
ggml_metal_init: skipping kernel_mul_mv_iq4_xs_f32                 (not supported)
ggml_metal_init: skipping kernel_mul_mv_id_f32_f32                 (not supported)
ggml_metal_init: skipping kernel_mul_mv_id_f16_f32                 (not supported)
ggml_metal_init: skipping kernel_mul_mv_id_bf16_f32                (not supported)
ggml_metal_init: skipping kernel_mul_mv_id_q4_0_f32                (not supported)
ggml_metal_init: skipping kernel_mul_mv_id_q4_1_f32                (not supported)
ggml_metal_init: skipping kernel_mul_mv_id_q5_0_f32                (not supported)
ggml_metal_init: skipping kernel_mul_mv_id_q5_1_f32                (not supported)
ggml_metal_init: skipping kernel_mul_mv_id_q8_0_f32                (not supported)
ggml_metal_init: skipping kernel_mul_mv_id_q2_K_f32                (not supported)
ggml_metal_init: skipping kernel_mul_mv_id_q3_K_f32                (not supported)
ggml_metal_init: skipping kernel_mul_mv_id_q4_K_f32                (not supported)
ggml_metal_init: skipping kernel_mul_mv_id_q5_K_f32                (not supported)
ggml_metal_init: skipping kernel_mul_mv_id_q6_K_f32                (not supported)
ggml_metal_init: skipping kernel_mul_mv_id_iq2_xxs_f32             (not supported)
ggml_metal_init: skipping kernel_mul_mv_id_iq2_xs_f32              (not supported)
ggml_metal_init: skipping kernel_mul_mv_id_iq3_xxs_f32             (not supported)
ggml_metal_init: skipping kernel_mul_mv_id_iq3_s_f32               (not supported)
ggml_metal_init: skipping kernel_mul_mv_id_iq2_s_f32               (not supported)
ggml_metal_init: skipping kernel_mul_mv_id_iq1_s_f32               (not supported)
ggml_metal_init: skipping kernel_mul_mv_id_iq1_m_f32               (not supported)
ggml_metal_init: skipping kernel_mul_mv_id_iq4_nl_f32              (not supported)
ggml_metal_init: skipping kernel_mul_mv_id_iq4_xs_f32              (not supported)
ggml_metal_init: skipping kernel_mul_mm_f32_f32                    (not supported)
ggml_metal_init: skipping kernel_mul_mm_f16_f32                    (not supported)
ggml_metal_init: skipping kernel_mul_mm_bf16_f32                   (not supported)
ggml_metal_init: skipping kernel_mul_mm_q4_0_f32                   (not supported)
ggml_metal_init: skipping kernel_mul_mm_q4_1_f32                   (not supported)
ggml_metal_init: skipping kernel_mul_mm_q5_0_f32                   (not supported)
ggml_metal_init: skipping kernel_mul_mm_q5_1_f32                   (not supported)
ggml_metal_init: skipping kernel_mul_mm_q8_0_f32                   (not supported)
ggml_metal_init: skipping kernel_mul_mm_q2_K_f32                   (not supported)
ggml_metal_init: skipping kernel_mul_mm_q3_K_f32                   (not supported)
ggml_metal_init: skipping kernel_mul_mm_q4_K_f32                   (not supported)
ggml_metal_init: skipping kernel_mul_mm_q5_K_f32                   (not supported)
ggml_metal_init: skipping kernel_mul_mm_q6_K_f32                   (not supported)
ggml_metal_init: skipping kernel_mul_mm_iq2_xxs_f32                (not supported)
ggml_metal_init: skipping kernel_mul_mm_iq2_xs_f32                 (not supported)
ggml_metal_init: skipping kernel_mul_mm_iq3_xxs_f32                (not supported)
ggml_metal_init: skipping kernel_mul_mm_iq3_s_f32                  (not supported)
ggml_metal_init: skipping kernel_mul_mm_iq2_s_f32                  (not supported)
ggml_metal_init: skipping kernel_mul_mm_iq1_s_f32                  (not supported)
ggml_metal_init: skipping kernel_mul_mm_iq1_m_f32                  (not supported)
ggml_metal_init: skipping kernel_mul_mm_iq4_nl_f32                 (not supported)
ggml_metal_init: skipping kernel_mul_mm_iq4_xs_f32                 (not supported)
ggml_metal_init: skipping kernel_mul_mm_id_f32_f32                 (not supported)
ggml_metal_init: skipping kernel_mul_mm_id_f16_f32                 (not supported)
ggml_metal_init: skipping kernel_mul_mm_id_bf16_f32                (not supported)
ggml_metal_init: skipping kernel_mul_mm_id_q4_0_f32                (not supported)
ggml_metal_init: skipping kernel_mul_mm_id_q4_1_f32                (not supported)
ggml_metal_init: skipping kernel_mul_mm_id_q5_0_f32                (not supported)
ggml_metal_init: skipping kernel_mul_mm_id_q5_1_f32                (not supported)
ggml_metal_init: skipping kernel_mul_mm_id_q8_0_f32                (not supported)
ggml_metal_init: skipping kernel_mul_mm_id_q2_K_f32                (not supported)
ggml_metal_init: skipping kernel_mul_mm_id_q3_K_f32                (not supported)
ggml_metal_init: skipping kernel_mul_mm_id_q4_K_f32                (not supported)
ggml_metal_init: skipping kernel_mul_mm_id_q5_K_f32                (not supported)
ggml_metal_init: skipping kernel_mul_mm_id_q6_K_f32                (not supported)
ggml_metal_init: skipping kernel_mul_mm_id_iq2_xxs_f32             (not supported)
ggml_metal_init: skipping kernel_mul_mm_id_iq2_xs_f32              (not supported)
ggml_metal_init: skipping kernel_mul_mm_id_iq3_xxs_f32             (not supported)
ggml_metal_init: skipping kernel_mul_mm_id_iq3_s_f32               (not supported)
ggml_metal_init: skipping kernel_mul_mm_id_iq2_s_f32               (not supported)
ggml_metal_init: skipping kernel_mul_mm_id_iq1_s_f32               (not supported)
ggml_metal_init: skipping kernel_mul_mm_id_iq1_m_f32               (not supported)
ggml_metal_init: skipping kernel_mul_mm_id_iq4_nl_f32              (not supported)
ggml_metal_init: skipping kernel_mul_mm_id_iq4_xs_f32              (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_f16_h64            (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_f16_h80            (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_f16_h96            (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_f16_h112           (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_f16_h128           (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_f16_h256           (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_bf16_h64           (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_bf16_h80           (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_bf16_h96           (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_bf16_h112          (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_bf16_h128          (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_bf16_h256          (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_q4_0_h64           (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_q4_0_h80           (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_q4_0_h96           (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_q4_0_h112          (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_q4_0_h128          (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_q4_0_h256          (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_q4_1_h64           (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_q4_1_h80           (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_q4_1_h96           (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_q4_1_h112          (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_q4_1_h128          (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_q4_1_h256          (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_q5_0_h64           (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_q5_0_h80           (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_q5_0_h96           (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_q5_0_h112          (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_q5_0_h128          (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_q5_0_h256          (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_q5_1_h64           (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_q5_1_h80           (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_q5_1_h96           (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_q5_1_h112          (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_q5_1_h128          (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_q5_1_h256          (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_q8_0_h64           (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_q8_0_h80           (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_q8_0_h96           (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_q8_0_h112          (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_q8_0_h128          (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_q8_0_h256          (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_vec_f16_h128       (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_vec_bf16_h128      (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_vec_q4_0_h128      (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_vec_q4_1_h128      (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_vec_q5_0_h128      (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_vec_q5_1_h128      (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_vec_q8_0_h128      (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_vec_f16_h256       (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_vec_bf16_h256      (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_vec_q4_0_h256      (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_vec_q4_1_h256      (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_vec_q5_0_h256      (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_vec_q5_1_h256      (not supported)
ggml_metal_init: skipping kernel_flash_attn_ext_vec_q8_0_h256      (not supported)
ggml_metal_init: skipping kernel_cpy_f32_bf16                      (not supported)
ggml_metal_init: skipping kernel_cpy_bf16_f32                      (not supported)
ggml_metal_init: skipping kernel_cpy_bf16_bf16                     (not supported)
whisper_backend_init: using BLAS backend
whisper_init_state: kv self size  =   18.87 MB
whisper_init_state: kv cross size =   56.62 MB
whisper_init_state: kv pad  size  =    4.72 MB
whisper_init_state: loading Core ML model from './models/ggml-small-encoder.mlmodelc'
whisper_init_state: first run on a device may take a while ...
whisper_init_state: Core ML model loaded
whisper_init_state: compute buffer (conv)   =    7.14 MB
whisper_init_state: compute buffer (cross)  =   10.79 MB
whisper_init_state: compute buffer (decode) =  102.77 MB

system_info: n_threads = 4 / 4 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | COREML = 1 | OPENVINO = 0 | 

main: processing './samples/jfk.wav' (176000 samples, 11.0 sec), 4 threads, 1 processors, 5 beams + best of 5, lang = en, task = transcribe, timestamps = 1 ...



whisper_print_timings:     load time =   886.34 ms
whisper_print_timings:     fallbacks =   5 p /   0 h
whisper_print_timings:      mel time =    36.53 ms
whisper_print_timings:   sample time =    11.16 ms /    30 runs (    0.37 ms per run)
whisper_print_timings:   encode time = 17493.50 ms /     1 runs (17493.50 ms per run)
whisper_print_timings:   decode time =     0.00 ms /     1 runs (    0.00 ms per run)
whisper_print_timings:   batchd time =   877.09 ms /    18 runs (   48.73 ms per run)
whisper_print_timings:   prompt time =     0.00 ms /     1 runs (    0.00 ms per run)
whisper_print_timings:    total time = 26046.72 ms
ggml_metal_free: deallocating
```

Why is it so that I don't receive the transcription output?
