### ISSUE TITLE
Escape Windows path seperator in JSON output

### ISSUE THREAD

**Issue by graham-walker** [ggerganov/whisper.cpp#769] opened 2023-04-15 22:24 UTC
When setting the model path on Windows using Windows path separators, the separator character is not escaped in the JSON output, resulting in invalid JSON. This issue is present in the 1.3.0 release.

Running:
`main --language english --model "D:\whisper.cpp 1.3.0\ggml-tiny.bin" --file "D:\whisper.cpp 1.3.0\audio_sample.wav" --output-file "D:\whisper.cpp 1.3.0\output" --output-json`

Results in the following invalid output in output.json:
```json
"params": {
  "model": "D:\whisper.cpp 1.3.0\ggml-tiny.bin",
  "language": "english",
  "translate": false
},
```

**Comment by tauseefmohammed2** [comment] 2023-04-16 09:55
Hi!
I would love to contribute to the repo. I saw that the issue is labelled "first time", which is perfect for me as I am new to this project and eager to get started. Could you please assign this issue to me?

**Closed** 2023-04-23 13:47 UTC
Labels: bug, good first issue
